/**
 * Generates the kernel's config. The plugin keeps this deliberately thin: it writes a
 * provider plus two groups and a handful of rules, and lets the kernel own everything
 * that is hard to keep correct — subscription parsing, node refresh, latency testing,
 * failover, and per-domain routing.
 *
 * Rejected alternatives, recorded so they are not re-attempted:
 *  - Parsing nodes in JS: the subscription can carry vmess/hysteria2/vless/ss, and its
 *    shape changes without notice. The kernel already parses it.
 *  - Hand-maintaining a China domain list in JS: inevitably incomplete, and it would
 *    shadow the kernel's own rules.
 *  - Ranking nodes by measured latency in JS: duplicates the `url-test` group and fights
 *    it for control of the same selection.
 */

/** Endpoint used for health checks and latency tests. Small, fast, and globally reachable. */
export const DEFAULT_TEST_URL = 'https://www.gstatic.com/generate_204'

/** Loopback so the API is never exposed on the LAN. */
export const DEFAULT_API_PORT = 17891

/**
 * The single group and provider the plugin references. Exported because the failover
 * watchdog must address the same names; keeping one source avoids the two silently
 * disagreeing after a rename.
 */
export const GROUP_NAME = 'auto'
export const PROVIDER_NAME = 'sub'

export function renderConfig(options) {
  const {
    port,
    apiPort,
    apiSecret,
    subscriptionUrl,
    providerMode = 'http',
    providerPath,
    testUrl = DEFAULT_TEST_URL,
    intervalSec = 3600,
    healthCheckSec = 300,
    groupName = GROUP_NAME,
  } = options

  const lines = []
  const push = (...values) => lines.push(...values)

  push(
    '# Generated by dsh-agentic-proxy. Edits are overwritten on every start.',
    `mixed-port: ${port}`,
    'allow-lan: false',
    'bind-address: 127.0.0.1',
    'mode: rule',
    'log-level: warning',
    'ipv6: false',
    'unified-delay: true',
    '',
    `external-controller: 127.0.0.1:${apiPort}`,
    `secret: "${apiSecret}"`,
    '',
  )

  // The kernel resolves node hostnames itself; public resolvers keep that off the local
  // resolver and avoid poisoning. nameserver-policy is intentionally absent so node
  // domains are resolved the same way as everything else.
  push(
    'dns:',
    '  enable: true',
    '  ipv6: false',
    '  enhanced-mode: fake-ip',
    '  fake-ip-range: 198.18.0.1/16',
    '  default-nameserver:',
    '    - 223.5.5.5',
    '    - 119.29.29.29',
    '  nameserver:',
    '    - https://223.5.5.5/dns-query',
    '    - https://doh.pub/dns-query',
    '  fallback:',
    '    - https://1.1.1.1/dns-query',
    '    - https://8.8.8.8/dns-query',
    '  fallback-filter:',
    '    geoip: false',
    '',
  )

  // `type: http` lets the kernel refetch on its own schedule. `type: file` points at a
  // copy the plugin fetched, which is the fallback when the provider endpoint rejects the
  // kernel's own User-Agent or when the user wants offline regeneration.
  push('proxy-providers:', '  sub:')
  if (providerMode === 'file') {
    push('    type: file', `    path: ${quote(slashPath(providerPath))}`)
  } else {
    push(
      '    type: http',
      `    url: ${quote(subscriptionUrl)}`,
      `    interval: ${intervalSec}`,
      `    path: ${quote(slashPath(providerPath))}`,
    )
  }
  push(
    '    health-check:',
    '      enable: true',
    `      url: ${testUrl}`,
    `      interval: ${healthCheckSec}`,
    '',
  )

  // A `url-test` group is what makes a dead node stop mattering: the kernel re-measures
  // and switches on its own, so the plugin never has to notice a failure itself.
  push(
    'proxy-groups:',
    `  - name: ${groupName}`,
    '    type: url-test',
    '    use:',
    '      - sub',
    `    url: ${testUrl}`,
    `    interval: ${healthCheckSec}`,
    '    tolerance: 50',
    '    lazy: false',
    '',
    '  - name: fallback',
    '    type: fallback',
    '    use:',
    '      - sub',
    `    url: ${testUrl}`,
    `    interval: ${healthCheckSec}`,
    '',
  )

  // Order matters. `lan` first keeps local traffic off the proxy no matter what the
  // later IP rules would otherwise decide; the domain suffix rule covers China sites
  // that a GeoIP lookup would miss, and `MATCH` is the catch-all.
  push(
    'rules:',
    '  - GEOIP,lan,DIRECT,no-resolve',
    '  - DOMAIN-SUFFIX,cn,DIRECT',
    '  - GEOIP,CN,DIRECT',
    `  - MATCH,${groupName}`,
    '',
  )

  return lines.join('\n')
}

/**
 * Single-quoted YAML, deliberately.
 *
 * A double-quoted scalar processes escapes, so a Windows path such as
 * `C:\Users\...` fails to parse: `\U` opens a unicode escape and the kernel reports
 * "did not find expected hexdecimal number". Single quotes are literal, and a single
 * quote inside is escaped by doubling it.
 */
function quote(value) {
  return `'${String(value).replace(/'/g, "''")}'`
}

/** mihomo accepts either separator; forward slashes avoid escaping questions entirely. */
export function slashPath(value) {
  return String(value).replace(/\\/g, '/')
}
